### ISSUE TITLE
get discord roles returns list of empty dicts

### ISSUE THREAD

**Issue by asdia0** [SpikeViper/SpookVooper.Api#20] opened 2020-11-26 14:12 UTC
https://api.spookvooper.com/User/GetDiscordRoles?SVID=u-1f4795a7-82f7-45bc-badd-84b50deb50f9 returns `[{},{},{},{},{},{},{},{},{},{}]` which isnt epic

**Comment by SpikeViper** [comment] 2020-11-26 15:12
Those are actually just empty objects, but I will find the root cause & fix

**Comment by SpikeViper** [comment] 2020-11-26 15:27
Closed in ad8a98c285c01388d00073d99a3ca7807ca2428a

**Comment by SpikeViper** [comment] 2020-11-26 15:28
Nuget package reflects change in 1.2.7

**Closed as completed by SpikeViper** 2020-11-26 15:27 UTC
